# Numpy Session

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh", 34.565,True]

In [8]:
a1 = np.array(l1)

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
a1.ndim     ## ndim() is used to return total n- Dimensional array. 

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.size   # size() is Used to return total element value in a array

7

In [18]:
a2.size

6

In [19]:
a3.size

9

In [20]:
a1.shape 

(7,)

In [21]:
a2.shape     #  shape() is used to return how much row & column are their in a array (ex:- 2 row & 3 Column)

(2, 3)

In [22]:
a3.shape  #  Read loud as this :- Read this array (1,3,3)  :- 3 cross 3 & one such kind of dimension.

(1, 3, 3)

In [31]:
np.random.randint(2,50)    # random.randint() is used to generate a random integer number.

28

In [33]:
np.random.randint(2,50, (2,3,4) ) # Read this array (2,3,4) :- 3 cross 4 & 2 such kind of dimension.

array([[[47, 18, 37, 29],
        [35, 19, 25, 12],
        [10, 26, 36, 23]],

       [[ 7, 16, 44, 27],
        [44, 36, 38, 11],
        [ 2, 19,  4, 48]]])

In [39]:
np.random.rand(2,3)

array([[0.62811405, 0.51162987, 0.53413348],
       [0.15080351, 0.64835324, 0.75896518]])

In [42]:
a4 = np.random.randn(4,4)

In [43]:
a4

array([[-0.12474031,  2.46938731, -0.51695244, -0.44089665],
       [-0.40766398, -2.23878575,  1.010266  ,  0.03449707],
       [-0.58144862,  0.27351155,  0.4091057 , -1.36860124],
       [-0.10287466,  0.41764524, -0.94972585, -2.45130029]])

In [46]:
a4.reshape(2,8) # reshape() is used to change the shape of previous array.

array([[-0.12474031,  2.46938731, -0.51695244, -0.44089665, -0.40766398,
        -2.23878575,  1.010266  ,  0.03449707],
       [-0.58144862,  0.27351155,  0.4091057 , -1.36860124, -0.10287466,
         0.41764524, -0.94972585, -2.45130029]])

In [47]:
a4.reshape(8,2)

array([[-0.12474031,  2.46938731],
       [-0.51695244, -0.44089665],
       [-0.40766398, -2.23878575],
       [ 1.010266  ,  0.03449707],
       [-0.58144862,  0.27351155],
       [ 0.4091057 , -1.36860124],
       [-0.10287466,  0.41764524],
       [-0.94972585, -2.45130029]])

In [48]:
a4.reshape(2,-1) # Any negative number will automatically shape of a Factorial number.

array([[-0.12474031,  2.46938731, -0.51695244, -0.44089665, -0.40766398,
        -2.23878575,  1.010266  ,  0.03449707],
       [-0.58144862,  0.27351155,  0.4091057 , -1.36860124, -0.10287466,
         0.41764524, -0.94972585, -2.45130029]])

In [49]:
a4.reshape(2,2,4)

array([[[-0.12474031,  2.46938731, -0.51695244, -0.44089665],
        [-0.40766398, -2.23878575,  1.010266  ,  0.03449707]],

       [[-0.58144862,  0.27351155,  0.4091057 , -1.36860124],
        [-0.10287466,  0.41764524, -0.94972585, -2.45130029]]])

In [50]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.12474031,  2.46938731, -0.51695244,
                -0.44089665],
               [-0.40766398, -2.23878575,  1.010266  ,
                 0.03449707]],

              [[-0.58144862,  0.27351155,  0.4091057 ,
                -1.36860124],
               [-0.10287466,  0.41764524, -0.94972585,
                -2.45130029]]]]]]]]]])

In [51]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [52]:
a1[0]

'4'

In [53]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [54]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [55]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [56]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [57]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a2[0]

array([1, 2, 3])

In [59]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [60]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [61]:
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

In [62]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [66]:
a5 = np.random.randint(2,90,(6,5))

In [67]:
a5

array([[15, 55, 11, 63, 22],
       [73, 40, 66, 54, 18],
       [15, 68, 89, 69, 72],
       [70, 65, 77, 23, 42],
       [34, 38, 81, 65, 63],
       [83, 61, 81, 25, 27]])

In [68]:
a5[a5>40]

array([55, 63, 73, 66, 54, 68, 89, 69, 72, 70, 65, 77, 42, 81, 65, 63, 83,
       61, 81])

In [69]:
a5

array([[15, 55, 11, 63, 22],
       [73, 40, 66, 54, 18],
       [15, 68, 89, 69, 72],
       [70, 65, 77, 23, 42],
       [34, 38, 81, 65, 63],
       [83, 61, 81, 25, 27]])

In [71]:
a5[0,1] = 100           # replace (0,1) ordinate value of 55 to 100.

In [72]:
a5

array([[ 15, 100,  11,  63,  22],
       [ 73,  40,  66,  54,  18],
       [ 15,  68,  89,  69,  72],
       [ 70,  65,  77,  23,  42],
       [ 34,  38,  81,  65,  63],
       [ 83,  61,  81,  25,  27]])

In [73]:
a6 = np.random.randint(0,3,(3,3))

In [74]:
a7 = np.random.randint(0,3,(3,3))

In [75]:
a6

array([[2, 1, 2],
       [1, 1, 0],
       [2, 1, 2]])

In [76]:
a7

array([[1, 2, 2],
       [1, 1, 2],
       [0, 0, 0]])

In [77]:
a6*a7             # Symbol * is used to give element wise multiplication.

array([[2, 2, 4],
       [1, 1, 0],
       [0, 0, 0]])

In [78]:
a6@a7              # @ symbol is used to give Matrix  multiplication.

array([[3, 5, 6],
       [2, 3, 4],
       [3, 5, 6]])

In [79]:
a6

array([[2, 1, 2],
       [1, 1, 0],
       [2, 1, 2]])

In [80]:
a6+100

array([[102, 101, 102],
       [101, 101, 100],
       [102, 101, 102]])

In [81]:
a6*2

array([[4, 2, 4],
       [2, 2, 0],
       [4, 2, 4]])

In [82]:
a6/0

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_12100/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Lenovo\AppData\Local\Temp/ipykernel_12100/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [inf, inf, nan],
       [inf, inf, inf]])

In [83]:
a6

array([[2, 1, 2],
       [1, 1, 0],
       [2, 1, 2]])

In [84]:
a6**3

array([[8, 1, 8],
       [1, 1, 0],
       [8, 1, 8]], dtype=int32)

In [86]:
a8 = np.zeros((4,4))

In [87]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
a9 = np.ones((4,5))

In [90]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [92]:
a9 + np.array([1,2,3,4,5])  # this function is called Broadcasting operation.

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [93]:
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [94]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [99]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [98]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [100]:
a6

array([[2, 1, 2],
       [1, 1, 0],
       [2, 1, 2]])

In [101]:
a6.T # T is a Transpose function for transporting array froom Row to column & wis

array([[2, 1, 2],
       [1, 1, 1],
       [2, 0, 2]])

In [103]:
a5

array([[ 15, 100,  11,  63,  22],
       [ 73,  40,  66,  54,  18],
       [ 15,  68,  89,  69,  72],
       [ 70,  65,  77,  23,  42],
       [ 34,  38,  81,  65,  63],
       [ 83,  61,  81,  25,  27]])

In [102]:
np.sqrt(a5)

array([[ 3.87298335, 10.        ,  3.31662479,  7.93725393,  4.69041576],
       [ 8.54400375,  6.32455532,  8.1240384 ,  7.34846923,  4.24264069],
       [ 3.87298335,  8.24621125,  9.43398113,  8.30662386,  8.48528137],
       [ 8.36660027,  8.06225775,  8.77496439,  4.79583152,  6.4807407 ],
       [ 5.83095189,  6.164414  ,  9.        ,  8.06225775,  7.93725393],
       [ 9.11043358,  7.81024968,  9.        ,  5.        ,  5.19615242]])

In [104]:
np.exp(a5)

array([[3.26901737e+06, 2.68811714e+43, 5.98741417e+04, 2.29378316e+27,
        3.58491285e+09],
       [5.05239363e+31, 2.35385267e+17, 4.60718663e+28, 2.83075330e+23,
        6.56599691e+07],
       [3.26901737e+06, 3.40427605e+29, 4.48961282e+38, 9.25378173e+29,
        1.85867175e+31],
       [2.51543867e+30, 1.69488924e+28, 2.75851345e+33, 9.74480345e+09,
        1.73927494e+18],
       [5.83461743e+14, 3.18559318e+16, 1.50609731e+35, 1.69488924e+28,
        2.29378316e+27],
       [1.11286375e+36, 3.10429794e+26, 1.50609731e+35, 7.20048993e+10,
        5.32048241e+11]])

In [105]:
np.log10(a5)

array([[1.17609126, 2.        , 1.04139269, 1.79934055, 1.34242268],
       [1.86332286, 1.60205999, 1.81954394, 1.73239376, 1.25527251],
       [1.17609126, 1.83250891, 1.94939001, 1.83884909, 1.8573325 ],
       [1.84509804, 1.81291336, 1.88649073, 1.36172784, 1.62324929],
       [1.53147892, 1.5797836 , 1.90848502, 1.81291336, 1.79934055],
       [1.91907809, 1.78532984, 1.90848502, 1.39794001, 1.43136376]])

In [106]:
range(10)

range(0, 10)

In [107]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [109]:
np.arange(10) # arange() is same function as range work.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.arange(1.8,10.7,2.5)  # arange() is uses in float value also.

array([1.8, 4.3, 6.8, 9.3])

In [114]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [113]:
np.logspace(2,4, num =4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [115]:
np.eye(5) # Eye() is use for generating identical matrix where Diagonal of matrix will be 1 and rest Element will be zero.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Data Visualisation via python

In [118]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [117]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68734 sha256=40b95db486e47f2c2e999fce5aadbefb4bcfb67b58a7972f556380d8e718ae9c
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [119]:
cf.go_offline()

In [120]:
np.random.randn(100,3)

array([[-0.44725907, -0.05016695,  0.16044098],
       [-1.44971956, -0.32587361,  0.72735392],
       [-0.62681798, -0.92740461,  0.14618714],
       [-1.43616686,  0.28926898,  0.24022676],
       [-0.40102636,  1.38647942,  1.03141375],
       [ 1.22338195, -0.89523257,  0.08035963],
       [-0.01589136,  1.41563034, -1.38564729],
       [ 0.94250955, -1.11495403, -0.97553815],
       [ 0.47193692,  0.39412325, -0.17424418],
       [ 0.29300183,  0.2002208 ,  1.42958812],
       [-0.51478275, -0.80793402, -0.47488283],
       [-0.01970105, -1.5165719 , -1.32370376],
       [-0.63414265, -0.1446404 ,  0.07700807],
       [ 1.90448947,  2.31221838, -0.77561999],
       [-1.43271338, -0.22500914,  1.79778079],
       [ 0.9853682 , -0.54394369, -1.40820877],
       [ 0.56086784, -0.97687863, -0.24653176],
       [-1.92011258,  0.19797125, -0.85494765],
       [ 1.1589503 ,  0.04764769,  2.02795334],
       [-2.495084  , -0.1641513 ,  0.78603313],
       [ 0.69047706,  0.85451557,  0.933

In [166]:
df = pd.DataFrame(np.random.randn(100,3))

In [167]:
df.iplot()

In [161]:
# df1= pd.DataFrame((np.random.randint(100,3)))

In [140]:
df

0         1         2
0  -1.030379 -1.074618  1.542819
1   1.815515 -1.661476  0.187078
2  -0.364007  0.463691 -1.193326
3   0.640636 -0.855899  0.383407
4   0.595005 -0.263212  0.271673
..       ...       ...       ...
95  1.317567 -1.437718  0.814652
96  1.701541 -1.936052  0.945730
97 -1.272843 -2.258562  0.274852
98  1.326904 -0.837340 -1.137766
99  0.241874 -0.638543  1.063049

[100 rows x 3 columns]

In [144]:
df2 = sns.load_dataset('titanic')

In [145]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [147]:
df2.iplot(x ='age' , y = 'fare', mode = 'markers')

In [148]:
df2.iplot(x ='age' , y = 'pclass', mode = 'markers')

In [149]:
df2.iplot(x ='fare' , y = 'pclass', mode = 'markers')

In [150]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [162]:
df2.iplot(kind = 'bar' , x ='fare' , y = 'pclass' )